#!/usr/bin/env python3
"""Generate SDL_DYNAMIC_API jump-table slot numbers for Katzensteg.

SDL's dynamic API jump table is a struct of function pointers laid out in the
order of src/dynapi/SDL_dynapi_procs.h. SDL only appends to that file, so a
slot number taken from one release is valid for every later release of the
same major version whose table is large enough. SDL2's list has
platform-conditional entries, so its slots differ between Windows, Linux and
macOS; SDL3's list has none.

The functions to number are the entries of the given X-macro lists
(KS_REAL(...), KS_REAL_VOID(...) and KS_WRAP(...)).

    gen_dynapi_slots.py --sdl 2 --version 2.32.10 \\
        --procs SDL2-2.32.10/src/dynapi/SDL_dynapi_procs.h \\
        --names src/katzensteg/real_sdl2_functions.h \\
        --names src/katzensteg/interpose_sdl2_dynapi_functions.h \\
        --output src/katzensteg/sdl2_dynapi_slots.h
"""

import argparse
import re
import sys

PROC = re.compile(r"^\s*SDL_DYNAPI_PROC\(\s*[^,]+,\s*(\w+)\s*,")
NAME = re.compile(r"^\s*KS_(?:REAL|REAL_VOID|WRAP)\(\s*(\w+)")

# Macros the SDL headers define on each target, for the conditionals that
# appear in SDL_dynapi_procs.h.
SDL2_PLATFORMS = {
    "windows": ("_WIN32", {"__WIN32__", "HAVE_STDIO_H"}),
    "linux": ("__linux__", {"__LINUX__", "HAVE_STDIO_H"}),
    "macos": ("__APPLE__", {"__MACOSX__", "HAVE_STDIO_H"}),
}


def evaluate(condition, defined):
    """Evaluates the #if forms SDL_dynapi_procs.h uses."""
    condition = condition.strip()
    expr = re.sub(r"defined\s*\(\s*(\w+)\s*\)", lambda m: "True" if m.group(1) in defined else "False", condition)
    expr = expr.replace("||", " or ").replace("&&", " and ").replace("!", " not ")
    if not re.fullmatch(r"[\sA-Za-z()]*", expr) or re.search(r"\b(?!True\b|False\b|or\b|and\b|not\b)\w+", expr):
        raise ValueError(f"unsupported conditional: {condition}")
    return eval(expr)  # noqa: S307 - validated to booleans and operators


def table_order(procs_text, defined):
    """Function names in jump-table order with `defined` macros set."""
    names = []
    # Each frame: (this branch active, some branch already taken, parent active).
    stack = []
    active = True
    for line in procs_text.splitlines():
        stripped = line.strip()
        directive = re.match(r"#\s*(\w+)\s*(.*)", stripped)
        if directive:
            kind, rest = directive.groups()
            if kind in ("if", "ifdef", "ifndef"):
                if kind == "ifdef":
                    value = rest.split()[0] in defined
                elif kind == "ifndef":
                    # Only SDL_DYNAPI_PROC_NO_VARARGS and header guards; the
                    # jump table includes the varargs entries.
                    value = rest.split()[0] not in defined
                else:
                    # Conditions inside an inactive block are not evaluated.
                    value = active and evaluate(rest, defined)
                stack.append((active, value))
                active = active and value
            elif kind == "elif":
                parent, taken = stack[-1]
                value = parent and not taken and evaluate(rest, defined)
                stack[-1] = (parent, taken or value)
                active = parent and value
            elif kind == "else":
                parent, taken = stack[-1]
                stack[-1] = (parent, True)
                active = parent and not taken
            elif kind == "endif":
                parent, _ = stack.pop()
                active = parent
            continue
        if not active:
            continue
        match = PROC.match(line)
        if match:
            names.append(match.group(1))
    if stack:
        raise ValueError("unbalanced conditionals")
    return names


def wanted_names(paths):
    names = []
    for path in paths:
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                match = NAME.match(line)
                if match and match.group(1) not in names:
                    names.append(match.group(1))
    return names


def slot_lines(order, names, prefix):
    lines = []
    for name in names:
        if name not in order:
            # Katzensteg's lists carry a few names this SDL no longer has
            # (SDL3 dropped SDL_GetRendererInfo). No slot: never wrapped, and
            # the real-function backend reports it if it is ever called.
            print(f"warning: {name} is not in the SDL dynamic API", file=sys.stderr)
            lines.append(f"#define {prefix}{name} 0xffffffffu /* not in this SDL's dynamic API */")
            continue
        lines.append(f"#define {prefix}{name} {order.index(name)}")
    return lines


def render(sdl, version, procs_text, names):
    prefix = f"KS_SDL{sdl}_SLOT_"
    out = [
        f"/* Generated by scripts/katzensteg/gen_dynapi_slots.py from SDL {version}",
        " * src/dynapi/SDL_dynapi_procs.h. Do not edit by hand.",
        " * Slot = index of the function pointer in SDL_DYNAPI_jump_table. */",
        "",
    ]
    if sdl == 2:
        first = True
        for platform, (guard, defined) in SDL2_PLATFORMS.items():
            out.append(f"#{'if' if first else 'elif'} defined({guard}) /* {platform} */")
            out.extend(slot_lines(table_order(procs_text, defined), names, prefix))
            first = False
        out.append("#else")
        out.append('#error "no SDL2 dynamic API slot numbers for this platform"')
        out.append("#endif")
    else:
        out.extend(slot_lines(table_order(procs_text, set()), names, prefix))
    return "\n".join(out) + "\n"


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sdl", type=int, choices=(2, 3), required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--procs", required=True)
    parser.add_argument("--names", action="append", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    with open(args.procs, encoding="utf-8") as handle:
        procs_text = handle.read()
    text = render(args.sdl, args.version, procs_text, wanted_names(args.names))
    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
